version: "3.8"

services:
  api:
    build: .

    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
      - /src/app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWOR: phprs
      MYSQL_DATABASE: phprs
      MYSQL_USER: phprs
      MYSQL_PASSWORD: phprs
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PHP_HOST: db
      MYSQL_ROOT_PASSWORD: phprs

volumes:
  db_data:
  portainer_data:
